services:
    nejo_twig_extensions.placeholdr:
      class: Nejo\PlaceholdrTwigExtensionBundle\Twig\Extension\PlaceholdrTwigExtension
      public: false
      tags:
        - { name: twig.extension }