language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

before_script:
  - sh ./Tests/bin/before_build.sh

script: phpunit --coverage-text

notifications:
  email:
    on_success: always
    on_failure: always